### ISSUE TITLE
How do you change the style?

### ISSUE THREAD

**Issue by agarrharr** [Wandmalfarbe/evangelion-clock-screensaver#1]
I installed it and it's in red. Is there an option for the normal style?

**Comment by Wandmalfarbe** [comment]
Currently not. I don’t know how to make an options page with Objective C.

**Comment by Froren** [comment]
I discovered this today with the help of a colleague. The .saver file is a directory you can open up. 

Go into `index.html` in `WebView` and replace the `svg` section with the code from `evangelion-optimized.svg`

**Comment by Wandmalfarbe** [comment]
Style selection is supported in the latest version.
