### ISSUE TITLE
Screensaver is cropped.

### ISSUE THREAD

**Issue by soarn** [Wandmalfarbe/evangelion-clock-screensaver#3]
Style does not affect it, but the saver is cut off at the bottom of the screen, I don't know if this is because of my macbook pro's weird screen size, but it's a minor annoyance.
*Screen size: 13.3IN (1280 x 800)*
![IMG_8952](https://user-images.githubusercontent.com/11000195/59535431-d07b4b80-8ea5-11e9-89f5-8acaa3d913fd.jpg)

**Comment by soarn** [comment]
I was going to edit the file, to see if I could find a fix, but I am absolutely lost in the file.  I used what was said in issue #1 and opened the file, but I'm lost, Even with an html beautifier.

**Comment by Wandmalfarbe** [comment]
It' a minified file not meant for editing. Im going to have a look today.
