### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by timdeplatvis111** [Wandmalfarbe/evangelion-clock-screensaver#5]
There is no file with the extension: .saver

**Comment by Wandmalfarbe** [comment]
It's a mac screensaver that can only be installed on macOS. Installation Instructions are in the readme:

> # Installation
> - Download the [latest version](https://github.com/Wandmalfarbe/evangelion-clock-screensaver/releases/latest) of the screensaver from the releases page.
> - Extract the ZIP file by double-clicking on it.
> - Install the screensaver by double-clicking on the file with the extension .saver.

You have to download the file `Evangelion-Clock-1.1.1.saver.zip`.
