### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by SergioSaver** [Wandmalfarbe/evangelion-clock-screensaver#9]
I'm just wondering if you'll ever make it comer to PC?

Thanks!

**Comment by Wandmalfarbe** [comment]
I have no experience in developing screensavers for Windows, so I won't develop a Windows port. But the screensaver is just a simple website that can be embedded easily. One can always fork this repo and embed the website into a Windows screensaver.

**Comment by SergioSaver** [comment]
I have zero experience with any of this stuff, do you think it's something
you can help me with? Or is there a website I can just open up?

**Comment by TheLastZombie** [comment]
I have no experience with packaging webpages into screensavers, but here's how I got it working in the browser:

- [Download](https://github.com/Wandmalfarbe/evangelion-clock-screensaver/archive/master.zip) and extract or [clone](https://www.git-scm.com/docs/git-clone) the repository
- Depending on if you want the normal or red version, open `webview\svg\style-normal.svg` or `webview\svg\style-red.svg` in a text editor of your choice and copy its contents
- Depending on if you want the 3D version or not, open `webview\html-template.html` or `webview\html-template-3d.html` with the text editor
- Replace `<!-- svg -->` with the code you just copied and overwrite the file

You can now open the file in your browser and should see the clock.
